import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { VedAnalytics } from 'ved-analytics';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <VedAnalytics
          project={process.env.NEXT_PUBLIC_VED_PROJECT_ID as string}
          apiKey={process.env.NEXT_PUBLIC_VED_API_KEY as string}
        />
        {children}
      </body>
    </html>
  );
}
